#!/usr/bin/env bash


#Functions
# Hides the output of shell command 
    function suppress () { 
        /bin/rm --force /tmp/suppress.out 2> /dev/null; ${1+"$@"} > /tmp/suppress.out 2>&1 || cat /tmp/suppress.out; /bin/rm /tmp/suppress.out
    }

# Script to run 'sudo' command in bash function script
        function sudo_Root {
            local firstArg=$1
            if [ $(type -t $firstArg) = function ]
            then
                    shift && command sudo bash -c "$(declare -f $firstArg);$firstArg $*"
            else
                    command sudo "$@"
            fi
        }

##########################################################################
# macOS Script
# Wipe the GUI script, desktop shortcut, and Step1 script while not touching any of the users data
function remove_downloaded_scrips_and_confs {
    #rm -rf ~/Bitlinc/Scripts/Bitcoin_Installer_Step1
    rm -rf ~/Bitlinc/Scripts/macos_GUI.zip
    rm -rf ~/Desktop/Bitcoin\ Installer
    rm -rf ~/Bitlinc/Scripts/Bitcoin_Installer_Step1
    #rm -rf /Volumes/btc_drive/hdd/bitcoin/bitcoin.conf
    #rm -rf /Volumes/btc_drive/hdd/bitcoin/testnet3/bitcoin.conf
}

# Download the GUI script, desktop shortcut, and Step1 script
function download_all_scrips_and_confs {
    cd ~/Bitlinc/Scripts; wget  https://github.com/bitlinc/Raspi_Node_Installer/raw/master/macos_GUI.zip
    ditto -x -v -k --sequesterRsrc ~/Bitlinc/Scripts/macos_GUI.zip ~/Desktop
    cd ~/Bitlinc/Scripts; wget https://raw.githubusercontent.com/bitlinc/Raspi_Node_Installer/master/Bitcoin_Installer_Step1
    chmod a+x ~/Bitlinc/Scripts/Bitcoin_Installer_Step1
    rm -rf ~/Desktop/Start\ Bitcoin\ Installer.command
}

suppress remove_downloaded_scrips_and_confs
suppress download_all_scrips_and_confs
